workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60

    integrations:
      app_store_connect: codemagic

    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jamal.studentbehavior

    scripts:
      - name: Get packages
        script: |
          flutter pub get

      - name: Apply signing
        script: |
          xcode-project use-profiles

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

      - name: Export IPA
        script: |
          xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner

    artifacts:
      - build/ios/ipa/*.ipa

publishing:
  app_store_connect:
    auth: integration
    submit_to_testflight: true