// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0uL2RWx5ykw0srj_N_C5z5HfKgdmDj-0',
    appId: '1:897875266644:ios:aa7190622b2d3cf69931c1',
    messagingSenderId: '897875266644',
    projectId: 'student-behavior-4833f',
    storageBucket: 'student-behavior-4833f.firebasestorage.app',
    iosBundleId: 'com.example.studentBehaviorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7JC58Y9TG5MtxcVw-L9WWocjL6F1O6pQ',
    appId: '1:897875266644:web:3f17e017c9ae16179931c1',
    messagingSenderId: '897875266644',
    projectId: 'student-behavior-4833f',
    authDomain: 'student-behavior-4833f.firebaseapp.com',
    storageBucket: 'student-behavior-4833f.firebasestorage.app',
    measurementId: 'G-RKG6GPLEEX',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7JC58Y9TG5MtxcVw-L9WWocjL6F1O6pQ',
    appId: '1:897875266644:web:3f17e017c9ae16179931c1',
    messagingSenderId: '897875266644',
    projectId: 'student-behavior-4833f',
    authDomain: 'student-behavior-4833f.firebaseapp.com',
    storageBucket: 'student-behavior-4833f.firebasestorage.app',
    measurementId: 'G-RKG6GPLEEX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0uL2RWx5ykw0srj_N_C5z5HfKgdmDj-0',
    appId: '1:897875266644:ios:b2fd0f088d2ae2b59931c1',
    messagingSenderId: '897875266644',
    projectId: 'student-behavior-4833f',
    storageBucket: 'student-behavior-4833f.firebasestorage.app',
    iosBundleId: 'com.jamal.studentbehavior',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVwtiTlIy6N0H48yF5lqrS8FBl2RwI-Qo',
    appId: '1:897875266644:android:e4a02b975ccaff579931c1',
    messagingSenderId: '897875266644',
    projectId: 'student-behavior-4833f',
    storageBucket: 'student-behavior-4833f.firebasestorage.app',
  );

}